name: 'Nice Repo Services: deploy and promote'
description: 'Deploy and promote a container image through GitOps / DevOps repository.'

branding:
  icon: power
  color: purple

inputs:
  image-tag:
    description: "Tag of image to deploy"
    required: true
  
  path-scheme:
    description: "Path scheme for app. E.g. {base}/{namespace}/{app}/{env}. Default: {base}/{namespace}/{app}/{env}"
    required: false
    default: "{base}/{namespace}/{app}/{env}"

  image-file:
    description: "Name of file which contain the container image and version tag. Default: deployment.yaml"
    required: false
    default: "deployment.yaml"

  app:
    description: "Name of app in path"
    required: true

  env:
    description: "Environment of app if needed for path scheme."
    required: false
    default: '""'

  base:
    description: "Base path for app if needed for path scheme."
    required: false
    default: '""'

  namespace:
    description: "Namespace of app if needed for path scheme."
    required: false
    default: '""'

  cluster:
    description: "Cluster of app if needed for path scheme."
    required: false
    default: '""'

  src-path:
    description: "Source path of GitOps repository."
    required: false
    default: '""'

  git-url:
    description: "URL of GitOps repository."
    required: true

  git-user:
    description: "User name for GitOps repository."
    required: false
    default: "github-actions"

  git-email:
    description: "Email address for GitOps repository."
    required: false
    default: '""'

  git-shallow-checkout:
    description: "Shallow checkout of GitOps repository."
    required: false
    default: "true"

  git-token:
    description: "Token for GitOps repository."
    required: false
    default: '""'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/nice-pink/repo-services-deploy:latest'
  entrypoint: '/app/bin/deploy'
  args:
  - -app=${{ inputs.app }}
  - -namespace=${{ inputs.namespace }}
  - -env=${{ inputs.env }}
  - -base=${{ inputs.base }}
  - -cluster=${{ inputs.cluster }}
  - -srcPath=${{ inputs.src-path }}
  - -tag=${{ inputs.image-tag }}
  - -pathScheme=${{ inputs.path-scheme }}
  - -gitUrl=${{ inputs.git-url }}
  - -gitUser=${{ inputs.git-user }}
  - -gitEmail=${{ inputs.git-email }}
  - -gitShallow=${{ inputs.git-shallow-checkout }}
  - -gitToken=${{ inputs.git-token }}
  - -gitPush
  
# runs:
#   using: "composite"
#   steps:
#     - name: Deploy image
#       shell: sh
#       run: |
#         go run ${{ github.action_path }}/cmd/deploy/main.go \
#           -app "${{ inputs.app }}" \
#           -namespace "${{ inputs.namespace }}" \
#           -env "${{ inputs.env }}" \
#           -base "${{ inputs.base }}" \
#           -cluster "${{ inputs.cluster }}" \
#           -src-path "${{ inputs.src-path }}" \
#           -git-push "${{ inputs.git-push }}" \
#           -tag "${{ inputs.image-tag }}" \
#           -path-scheme "${{ inputs.path-scheme }}"
